#!/bin/sh

#script to load and unload the driver
if [ ! $# -eq 1 ]
then
	usage
	exit 1
fi

if [ $1 = "load" ]
then
    echo "loading hw_serial UART module"
	mode="644"
	# Look for wheel or use staff
	if grep -q '^staff:' /etc/group; then
		group="staff"
	else
		group="wheel"
	fi

	# Create the device node
	module_uart_driver="hw_serial"
	device_uart_driver="hw_serial"

	# Install module
	insmod /lib/modules/4.14.40/extra/hw_serial.ko || exit 1
    
elif [ $1 = "unload" ]
then
    echo "Unloading hw_serial UART module"
	device_uart_driver="hw_serial"
	rmmod $device_uart_driver || exit 1
    
fi

